name: prag_cat_breed
description: "App to learn about cat breeds."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#0D1117"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: true
  fullscreen: true

  android_12:
    image: assets/splash_logo.png
    icon_background_color: "#0D1117"

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png


